import type { Product, User, KycStatus } from './types';
import { PlaceHolderImages } from './placeholder-images';

const users: User[] = [
  {
    id: 'user1',
    name: 'Alex Doe',
    avatarUrl: 'https://picsum.photos/seed/user1/100/100',
    rating: 4.8,
    reviews: 120,
    isPro: true,
    isWeb3Verified: false,
    kycStatus: 'Verified',
  },
  {
    id: 'user2',
    name: 'Billie Jean',
    avatarUrl: 'https://picsum.photos/seed/user2/100/100',
    rating: 4.9,
    reviews: 85,
    isPro: false,
    isWeb3Verified: true,
    kycStatus: 'Verified',
  },
  {
    id: 'user3',
    name: 'Charlie Brown',
    avatarUrl: 'https://picsum.photos/seed/user3/100/100',
    rating: 4.5,
    reviews: 42,
    isPro: true,
    isWeb3Verified: true,
    kycStatus: 'Verified',
  },
  {
    id: 'user4',
    name: 'Diana Prince',
    avatarUrl: 'https://picsum.photos/seed/user4/100/100',
    rating: 4.9,
    reviews: 210,
    isPro: true,
    isWeb3Verified: true,
    kycStatus: 'Not Verified',
  },
  {
    id: 'user5',
    name: 'Ethan Hunt',
    avatarUrl: 'https://picsum.photos/seed/user5/100/100',
    rating: 4.7,
    reviews: 150,
    isPro: true,
    kycStatus: 'Pending',
  },
  {
    id: 'user6',
    name: 'Fiona Glenanne',
    avatarUrl: 'https://picsum.photos/seed/user6/100/100',
    rating: 4.8,
    reviews: 95,
    isWeb3Verified: true,
    kycStatus: 'Verified',
  },
  {
    id: 'user7',
    name: 'George Costanza',
    avatarUrl: 'https://picsum.photos/seed/user7/100/100',
    rating: 4.3,
    reviews: 33,
    kycStatus: 'Verified',
  },
  {
    id: 'user8',
    name: 'Helen Troy',
    avatarUrl: 'https://picsum.photos/seed/user8/100/100',
    rating: 5.0,
    reviews: 18,
    isPro: false,
    isWeb3Verified: false,
    kycStatus: 'Not Verified',
  },
  {
    id: 'user9',
    name: 'Ivan Drago',
    avatarUrl: 'https://picsum.photos/seed/user9/100/100',
    rating: 4.6,
    reviews: 78,
    isPro: true,
    isWeb3Verified: true,
    kycStatus: 'Verified',
  },
  {
    id: 'user10',
    name: 'Jane Smith',
    avatarUrl: 'https://picsum.photos/seed/user10/100/100',
    rating: 4.9,
    reviews: 132,
    isPro: true,
    isWeb3Verified: true,
    kycStatus: 'Verified',
  },
];

const products: Product[] = [
  {
    id: 'vintage-camera',
    name: 'Vintage Film Camera',
    description: 'A classic 35mm film camera in excellent working condition. A true collector\'s item that still produces beautiful, grainy photos.',
    price: 6500,
    currency: 'THB',
    images: [PlaceHolderImages.find(p => p.id === 'vintage-camera')?.imageUrl || ''],
    imageHints: [PlaceHolderImages.find(p => p.id === 'vintage-camera')?.imageHint || ''],
    seller: users[0],
    location: { city: 'Bangkok', country: 'Thailand', lat: 13.7563, lng: 100.5018 },
    category: 'Electronics',
    likes: 132,
    favorites: 256,
  },
  {
    id: 'leather-wallet',
    name: 'Handmade Leather Wallet',
    description: 'A durable and stylish wallet crafted from genuine full-grain leather. Ages beautifully and holds all your essentials.',
    price: 650,
    currency: 'THB', // Was 120 RMB
    images: [PlaceHolderImages.find(p => p.id === 'leather-wallet')?.imageUrl || ''],
    imageHints: [PlaceHolderImages.find(p => p.id === 'leather-wallet')?.imageHint || ''],
    seller: users[1],
    location: { city: 'Shanghai', country: 'China', lat: 31.2304, lng: 121.4737 },
    category: 'Accessories',
    likes: 88,
    favorites: 150,
  },
  {
    id: 'smart-watch',
    name: 'Gen-5 Smart Watch',
    description: 'A sleek smart watch with fitness tracking, notifications, and a vibrant display. Compatible with both Android and iOS.',
    price: 5250,
    currency: 'THB', // Was 150 USDT
    images: [PlaceHolderImages.find(p => p.id === 'smart-watch')?.imageUrl || ''],
    imageHints: [PlaceHolderImages.find(p => p.id === 'smart-watch')?.imageHint || ''],
    seller: users[2],
    location: { city: 'Chiang Mai', country: 'Thailand', lat: 18.7883, lng: 98.9853 },
    category: 'Electronics',
    likes: 215,
    favorites: 430,
  },
  {
    id: 'wireless-headphones',
    name: 'Noise-Cancelling Headphones',
    description: 'Immerse yourself in sound with these premium noise-cancelling headphones. Long battery life and crystal-clear audio quality.',
    price: 8000,
    currency: 'THB',
    images: [PlaceHolderImages.find(p => p.id === 'wireless-headphones')?.imageUrl || ''],
    imageHints: [PlaceHolderImages.find(p => p.id === 'wireless-headphones')?.imageHint || ''],
    seller: users[0],
    location: { city: 'Phuket', country: 'Thailand', lat: 7.8804, lng: 98.3923 },
    category: 'Electronics',
    likes: 180,
    favorites: 320,
  },
  {
    id: 'designer-sunglasses',
    name: 'Designer Sunglasses',
    description: 'Protect your eyes in style with these authentic designer sunglasses. 100% UV protection and a timeless design.',
    price: 2340,
    currency: 'THB', // was 450 RMB
    images: [PlaceHolderImages.find(p => p.id === 'designer-sunglasses')?.imageUrl || ''],
    imageHints: [PlaceHolderImages.find(p => p.id === 'designer-sunglasses')?.imageHint || ''],
    seller: users[1],
    location: { city: 'Beijing', country: 'China', lat: 39.9042, lng: 116.4074 },
    category: 'Accessories',
    likes: 95,
    favorites: 180,
  },
  {
    id: 'gaming-console',
    name: 'Next-Gen Gaming Console',
    description: 'Experience the future of gaming with this powerful console. Barely used and comes with two controllers and all original cables.',
    price: 13200,
    currency: 'THB', // Was 400 USDT
    images: [PlaceHolderImages.find(p => p.id === 'gaming-console')?.imageUrl || ''],
    imageHints: [PlaceHolderImages.find(p => p.id === 'gaming-console')?.imageHint || ''],
    seller: users[2],
    location: { city: 'Pattaya', country: 'Thailand', lat: 12.9246, lng: 100.8825 },
    category: 'Electronics',
    isConsignment: true,
    likes: 500,
    favorites: 980,
  },
  {
    id: 'ceramic-vase',
    name: 'Hand-Painted Ceramic Vase',
    description: 'A beautiful, one-of-a-kind ceramic vase hand-painted by a local artist. A perfect centerpiece for any room.',
    price: 2500,
    currency: 'THB',
    images: [PlaceHolderImages.find(p => p.id === 'ceramic-vase')?.imageUrl || ''],
    imageHints: [PlaceHolderImages.find(p => p.id === 'ceramic-vase')?.imageHint || ''],
    seller: users[0],
    location: { city: 'Bangkok', country: 'Thailand', lat: 13.74, lng: 100.52 },
    category: 'Home Goods',
    likes: 45,
    favorites: 80,
  },
  {
    id: 'mountain-bike',
    name: 'Pro Mountain Bike',
    description: 'A high-performance mountain bike with a lightweight aluminum frame and full suspension. Ready for any trail.',
    price: 25000,
    currency: 'THB',
    images: [PlaceHolderImages.find(p => p.id === 'mountain-bike')?.imageUrl || ''],
    imageHints: [PlaceHolderImages.find(p => p.id === 'mountain-bike')?.imageHint || ''],
    seller: users[2],
    location: { city: 'Chiang Mai', country: 'Thailand', lat: 18.8, lng: 99.0 },
    category: 'Sports & Outdoors',
    likes: 120,
    favorites: 210,
  },
   {
    id: 'ukulele',
    name: 'Soprano Ukulele',
    description: 'A beautiful soprano ukulele with a warm, bright tone. Perfect for beginners and experienced players alike. Comes with a carrying case.',
    price: 2800,
    currency: 'THB',
    images: [PlaceHolderImages.find(p => p.id === 'ukulele')?.imageUrl || ''],
    imageHints: [PlaceHolderImages.find(p => p.id === 'ukulele')?.imageHint || ''],
    seller: users[3],
    location: { city: 'Bangkok', country: 'Thailand', lat: 13.75, lng: 100.51 },
    category: 'Musical Instruments',
    likes: 60,
    favorites: 110,
  },
  {
    id: 'drone',
    name: '4K Camera Drone',
    description: 'A high-quality quadcopter drone with a 4K camera. Stable flight, long battery life, and intuitive controls. Great for aerial photography and videography.',
    price: 15000,
    currency: 'THB',
    images: [PlaceHolderImages.find(p => p.id === 'drone')?.imageUrl || ''],
    imageHints: [PlaceHolderImages.find(p => p.id === 'drone')?.imageHint || ''],
    seller: users[4],
    location: { city: 'Chiang Mai', country: 'Thailand', lat: 18.79, lng: 98.99 },
    category: 'Electronics',
    likes: 350,
    favorites: 600,
  },
  {
    id: 'espresso-machine',
    name: 'Semi-Automatic Espresso Machine',
    description: 'A semi-automatic espresso machine for making cafe-quality coffee at home. Features a powerful steam wand for frothing milk.',
    price: 1820,
    currency: 'THB', // Was 350 RMB
    images: [PlaceHolderImages.find(p => p.id === 'espresso-machine')?.imageUrl || ''],
    imageHints: [PlaceHolderImages.find(p => p.id === 'espresso-machine')?.imageHint || ''],
    seller: users[5],
    location: { city: 'Shanghai', country: 'China', lat: 31.22, lng: 121.48 },
    category: 'Home Goods',
    likes: 190,
    favorites: 380,
  },
  {
    id: 'leather-backpack',
    name: 'Vintage Leather Backpack',
    description: 'A stylish and durable leather backpack with multiple compartments. Perfect for work, travel, or everyday use.',
    price: 6600,
    currency: 'THB', // Was 200 USDT
    images: [PlaceHolderImages.find(p => p.id === 'leather-backpack')?.imageUrl || ''],
    imageHints: [PlaceHolderImages.find(p => p.id === 'leather-backpack')?.imageHint || ''],
    seller: users[6],
    location: { city: 'Pattaya', country: 'Thailand', lat: 12.93, lng: 100.89 },
    category: 'Accessories',
    likes: 220,
    favorites: 450,
  },
];

export async function getProducts(): Promise<Product[]> {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 500));
  return products;
}

export async function getProductById(id: string): Promise<Product | undefined> {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 500));
  return products.find(p => p.id === id);
}

export async function getUsers(): Promise<User[]> {
    await new Promise(resolve => setTimeout(resolve, 500));
    return users;
}
